import Head from 'next/head'
import React, { useEffect } from 'react';
import HomeContainer from '../containers/HomeContainer'

export default function Home(initData) {
	return (
		<div className="container">
			<Head>
				<title>Giphy</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="this is a Giphy app. Find giphies quickly" />
			</Head>
			<HomeContainer data={initData.catGiphys.data} />
		</div>
	)
}


export async function getStaticProps() {
	let catGiphys = await fetch('https://api.giphy.com/v1/gifs/search?q=cats&api_key=fWsx77g2ZI5ssH0zX0n1lh91aLh0ev1Q&limit=10')
	catGiphys = await catGiphys.json()
	return { props: { catGiphys } }
}